//console.log('test');
//var User=require('./user.js');
//console.log(User);
//var user1=new User('Petro',22);
//user1.show();
// var Obj=require('./user.js');
// console.log(Obj);
// var user1=new User.func('Petro',22);
// user1.show();
var User=Obj.func;
var user1=new Obj.func('Ivan',23);
user1.show();